config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#root"

  resource :users
  resource :session, only: [:new, :create, :destroy]

  get 'auth/facebook/callback', to: 'sessions#omniauth_facebook'

  namespace :api, defaults: { format: :json } do
     resources :institutions
     resources :accounts
     resources :transactions
     resources :users
     resource :session
    get "search", to: "utils#search"
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController


  def root
  end


end

app/views/static_pages/oldroot.html.erb
<header class="root-header">
  <nav class="root-header-nav group">

    <ul class="root-header-list group">
      <li>
        <a href="#">Hi <%= current_user.email %></a>
      </li>
      <li><a href="#">Accounts</a></li>
      <li><form action="<%= session_url %>" method="post"><input
        type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="delete">
        <button>Log Out</button></form></li>

    </ul>

  </nav>
</header>

<div id="root">
  <h2> To give you the freshest possible info, your accounts are now updating… this will only take a moment. </h2>
</div>

<script type="text/javascript">
  document.addEventListener("DOMContentLoaded", function () {
    init();
  });
</script>

app/views/static_pages/root.html.erb
<div id="root">
  <h2> To give you the freshest possible info, your accounts are now updating… this will only take a moment. </h2>
</div>


<script type="text/javascript">
  $(function () {
    window.init();
  })
</script>

<script type="text/javascript">
  var host = "stevendikowitz.com";
  if ((host == window.location.host) && (window.location.protocol != "https:"))
      window.location.protocol = "https";
</script>