config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#root"

  resource :users
  resource :session, only: [:new, :create, :destroy]

  get 'auth/facebook/callback', to: 'sessions#omniauth_facebook'

  namespace :api, defaults: { format: :json } do
     resources :institutions
     resources :accounts
     resources :transactions
     resources :users
     resource :session
    get "search", to: "utils#search"
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :integer          not null, primary key
#  email               :string           not null
#  password_digest     :string           not null
#  session_token       :string           not null
#  created_at          :datetime
#  updated_at          :datetime
#  avatar_file_name    :string
#  avatar_content_type :string
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#  fname               :string
#  lname               :string
#  gender              :string
#  age                 :string
#  provider            :string
#  uid                 :string
#

class User < ActiveRecord::Base
  attr_reader :password

  has_attached_file :avatar, default_url: "missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  validates :email, :password_digest, :session_token, presence: true
  validates :email, uniqueness: true
  validates :email, format: { with: /\A([^@\s]+)@(([-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :password, length: { minimum: 6, allow_nil: true }
  validates_uniqueness_of :uid, scope: :provider, if: -> { uid }

  after_initialize :ensure_session_token

  #associations
  has_many :accounts, dependent: :destroy
  has_many :institutions, through: :accounts, source: :institution
  has_many :transactions, through: :accounts, source: :transactions


  def self.generate_session_token
   SecureRandom.urlsafe_base64
  end

  def reset_session_token!
   self.session_token = User.generate_session_token
   save!
  end

  def ensure_session_token
   self.session_token ||= User.generate_session_token
  end

  def password=(password)
   @password = password
   self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
   BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_or_create_by_auth_hash(auth_hash)

    provider = auth_hash.provider
    uid = auth_hash.uid

    user = User.find_by(provider: provider, uid: uid)
    return user if user

    user = User.new(provider: provider, uid: uid)
    user.fname = auth_hash.info.name.split(" ").first || ""
    user.lname = auth_hash.info.name.split(" ").last || ""
    user.password_digest = SecureRandom.urlsafe_base64

    if auth_hash.info.image
      avatar_url = process_uri(auth_hash.info.image)
      user.avatar = URI.parse(avatar_url)
    end

    user.email = auth_hash.info.name.gsub(" ", ".").downcase + "@facebook.com"
    user.save!
    user
  end

  def self.find_by_credentials(email, password)
   user = User.find_by_email(email)
   return nil unless user && user.is_password?(password)
   user
  end

  def self.process_uri(uri)
    require 'open-uri'
    require 'open_uri_redirections'
    open(uri, :allow_redirections => :safe) do |r|
      r.base_uri.to_s
    end
  end

end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController

  # before_action :redirect_logged_out_users

  def show
    @user = User.find(params[:id])
    render :show
  end

  def update
    @user = current_user
    @user.update!(user_params)
    render :show
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      render :show
    else
      render json: {errors: @user.errors.full_messages}.to_json, status: 422
    end
  end

  def destroy
   @user = current_user
   @user.destroy!
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :fname, :lname, :age, :gender, :avatar, :image_url)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :redirect_logged_in_users, only: [:new, :create]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
     log_in_user!(@user)
     flash[:message] = ["Welcome to Mintmo, #{@user.email}! Let's get started"]
     redirect_to root_url
    else
     flash.now[:errors] = @user.errors.full_messages
     render :new
    end
  end

  def update
    current_user.update!(user_params)
    render :show
  end

  private
  def redirect_logged_in_users
    if logged_in?
      redirect_to root_url
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :fname, :lname, :age, :avatar)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<header class="header">
  <nav class="header-nav group">

    <h1 class="header-logo">
      <a href="#"><img class="mintmo-logo" src="<%= asset_path('mintmo.png') %>" alt="" /></a>
    </h1>

    <ul class="header-list group">
      <li>
        <a href="<%= new_user_url %>" class="header-list-bold">Sign up</a>
      </li>
      <li><a href="<%= new_session_url %>">Log in</a></li>
    </ul>

  </nav>
</header>

<main class="content group">
  <section class="content-main">

    <h1 class="main-header">See all your finances in one place & create a budget</h1>

    <% if flash[:errors] %>
      <p class="errors" ><%= flash[:errors].join("<br>").html_safe %> </p>
    <% end%>

    <form class="form group" action="<%= user_url %>" method="post">
      <input type="hidden"
        name="authenticity_token"
        id=""
        value="<%= form_authenticity_token %>">

      <fieldset class="form-fieldset">

        <div class="input">
          <label for="form-email">Your Email</label>
          <input id="form-email" type="text" name="user[email]" value="<%= @user.email %>">
        </div>

        <div class="input">
          <label for="form-password">Password</label>
          <input id="form-password" type="password" name="user[password]" value="<%= @user.password %>">
        </div>

        <div class="submit">
          <button>SIGN UP</button>
        </div>
  </section>

  <section class="content-sidebar">

    <h1 class="sidebar-header">
      Why you'll love it
    </h1>

    <ul class="sidebar-list">
      <li>See all your accounts in one place</li>
      <li>Set a budget and pay down your debt</li>
      <li>Find the best ways to grow your money</li>
      <li>Stay safe and secure</li>
    </ul>
  </section>
</main>